# Generated by Django 3.2.7 on 2024-02-04 13:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='constituency',
            field=models.CharField(blank=True, choices=[('dgts', 'Dagoretti south'), ('dgtn', 'Dagoretti north'), ('thk', 'Thika'), ('kmb', 'Kiambu'), ('ktl', 'Kitengela'), ('kky', 'kikuyu'), ('klm', 'Kilimani')], max_length=15, null=True),
        ),
    ]
